import { BookOpen, MessageSquare } from "lucide-react";
import type { AnalysisDoc } from "@/lib/types";

export default function ReportPrintPage({ analysis }: { analysis: AnalysisDoc }) {
  return (
    <>
      {/* ── Visible Footer — Contest CTA + Contact ────────────────── */}
      <div className="mx-auto max-w-7xl px-6 py-10 no-print">
        <div className="rounded-2xl border border-blue-500/20 bg-gradient-to-r from-blue-500/5 via-blue-500/10 to-blue-500/5 p-6 text-center mb-6">
          <div className="flex items-center justify-center gap-3 mb-3">
            <div className="rounded-full bg-blue-500/15 p-2.5">
              <MessageSquare className="h-5 w-5 text-blue-400" />
            </div>
            <h3 className="text-lg font-bold text-zinc-100">Don&apos;t agree with the assessment?</h3>
          </div>
          <p className="text-sm text-zinc-300 max-w-xl mx-auto leading-relaxed">
            Please help us by <span className="text-blue-400 font-semibold">contesting the analysis in comments</span>.
            Every section above has a{" "}
            <span className="inline-flex items-center gap-1 bg-blue-500/10 border border-blue-500/20 rounded px-1.5 py-0.5 text-blue-400 text-xs font-medium">
              <MessageSquare className="h-3 w-3" /> Comment
            </span>{" "}
            button — click it to share your perspective.
          </p>
        </div>
        <p className="text-center text-xs text-zinc-500">
          Want to build such an agentic app? Contact{" "}
          <a href="mailto:contactbhasker7483@gmail.com" className="text-blue-400 hover:text-blue-300 underline">contactbhasker7483@gmail.com</a>
        </p>
      </div>

      {/* ── Print-Only Closing Page ───────────────────────────────── */}
      <section className="hidden print-only print-page-break bg-zinc-950 text-zinc-100 px-6 py-8">
        <div className="mx-auto max-w-3xl text-center">
          <BookOpen className="mx-auto h-8 w-8 text-blue-400 mb-3" />
          <h2 className="text-xl font-bold text-zinc-200 mb-2">
            Thank you for reviewing this assessment
          </h2>
          <p className="text-sm text-zinc-400 leading-relaxed mb-5">
            Generated by <span className="text-zinc-200 font-semibold">DocDetector</span> — an AI-powered
            document analysis engine evaluating business documents across decision modules,
            content forensics, bias detection, and more.
          </p>

          <div className="grid grid-cols-2 gap-3 mb-4">
            <div className="rounded-lg border border-zinc-800 bg-zinc-900/60 p-4 text-left">
              <h3 className="text-xs font-semibold text-zinc-300 uppercase tracking-wider mb-1.5">Assessment Rules</h3>
              <p className="text-xs text-zinc-400 mb-1">Full methodology & metric definitions:</p>
              <p className="text-xs text-blue-400 font-mono break-all">
                {typeof window !== "undefined" ? `${window.location.origin}/glossary/` : "https://documentworthanalyser.web.app/glossary/"}
              </p>
            </div>
            <div className="rounded-lg border border-zinc-800 bg-zinc-900/60 p-4 text-left">
              <h3 className="text-xs font-semibold text-zinc-300 uppercase tracking-wider mb-1.5">View Report Online</h3>
              <p className="text-xs text-zinc-400 mb-1">Interactive version with tooltips:</p>
              <p className="text-xs text-blue-400 font-mono break-all">
                {typeof window !== "undefined" ? window.location.href : ""}
              </p>
            </div>
          </div>

          <div className="rounded-lg border border-amber-500/20 bg-amber-500/5 p-4 text-left">
            <h3 className="text-xs font-semibold text-amber-400 uppercase tracking-wider mb-1">Have questions or disagree?</h3>
            <p className="text-xs text-zinc-400">
              Open the report online and use the <span className="text-zinc-200 font-medium">comment</span> feature
              on any section to share feedback. Every section has a discussion panel.
            </p>
          </div>

          <p className="mt-4 text-xs text-zinc-600">
            DocDetector &middot; {analysis.uploaded_at.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
          </p>
          <p className="mt-2 text-xs text-zinc-500">
            Want to build such an agentic app? Contact{" "}
            <a href="mailto:contactbhasker7483@gmail.com" className="text-blue-400 hover:text-blue-300 underline">contactbhasker7483@gmail.com</a>
          </p>
        </div>
      </section>
    </>
  );
}
